name:                aoc-hs
version:             0.1.0.0

extra-source-files:
  readme.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aoc-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-hs

tests:
  aoc-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-hs
